### ISSUE TITLE
Puerto 3306

### ISSUE THREAD

**Issue by fiturbe** [mosoriob/inf-323-questions#10]
Hola, me quedó una duda respecto al issue de la nueva máquina en donde se debe permitir conexión interna a través del puerto 3306, el tema es que al probar con  `netstat -lnp | grep mysql`:
```
tcp6       0      0 :::3306                 :::*                    LISTEN      993/mysqld          
unix  2      [ ACC ]     STREAM     LISTENING     19022    993/mysqld           /var/lib/mysql/mysql.sock
```
Como podemos ver está escuchando a través del puerto 3306 como se indica, la duda es si acaso hay que hacer alguna otra configuración en la base de datos o en las ip tables para que solamente acepte peticiones desde la segunda máquina?

He buscado documentación pero no me quedo muy claro

Saludos,

**Comment by mosoriob** [comment]
Está asociado al software, en nginx por ejemplo la sentencia se llama ** listen **
```
    listen 80;
    listen 127.0.0.1:80;
```

En mySQL sucede lo mismo, pero la sentencia se llama **bind-address**

https://www.cyberciti.biz/faq/unix-linux-mysqld-server-bind-to-more-than-one-ip-address/
