### ISSUE TITLE
Issue #18 Optimización base de datos (master)

### ISSUE THREAD

**Issue by DanQuin** [mosoriob/inf-323-questions#11]
Tengo una duda, el concepto `innodb_buffer_file_size` es el buscado? o es `innodb_log_file_size` porque he encontrado muy poca documentación del primero.

**Comment by mosoriob** [comment]
Si estimado, es un error. Debe ser innodb_log_file_size

**Comment by DanQuin** [comment]
Ok, muchas gracias.

Además, aprovecho de preguntar por:
- `query_cache` (supongo que *limit* y *size*?)
- `logging` (al proceso en sí? u un parámetro/opción?)

que tampoco aparecen en la documentación :|

**Comment by mosoriob** [comment]
Son:
- query_cache_size
- log_bin
