### ISSUE TITLE
configuracion via percona wizard(master)|

### ISSUE THREAD

**Issue by tigonza** [mosoriob/inf-323-questions#12]
Tengo un problema con la configuracion generada con percona, pues complete el campo de server-id en el paso correspondiente y ocurre esto al comenzar el servicio mysqld a traves de systemctl (
journalcl -xe):

    [Warning] Could not increase number of max_open_files to more than 5000 (request: 500 
    Nov 07 20:09:57 lc-ip123.inf.utfsm.cl mysqld[26907]: 2017-11-07T23:09:57.941094Z 0 [Warning] The use of InnoDB is mandatory since MySQL 5.7. The former options like '--innodb=0/1/OFF/ON' or '--skip-innodb' are ignored. 
    Nov 07 20:09:57 lc-ip123.inf.utfsm.cl mysqld[26907]: 2017-11-07T23:09:57.941148Z 0 [Warning] The syntax 'avoid_temporal_upgrade' is deprecated and will be removed in a future release
    Nov 07 20:09:57 lc-ip123.inf.utfsm.cl mysqld[26907]: 2017-11-07T23:09:57.941222Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
    Nov 07 20:09:57 lc-ip123.inf.utfsm.cl mysqld[26907]: 2017-11-07T23:09:57.945413Z 0 [Note] /usr/sbin/mysqld (mysqld 5.7.19-17-log) starting as process 26911 ...
    Nov 07 20:09:57 lc-ip123.inf.utfsm.cl mysqld[26907]: 2017-11-07T23:09:57.949983Z 0 [ERROR] You have enabled the binary log, but you haven't provided the mandatory server-id. Please refer to the proper server start-up parameters documentation
    Nov 07 20:09:57 lc-ip123.inf.utfsm.cl mysqld[26907]: 2017-11-07T23:09:57.950019Z 0 [ERROR] Aborting
    Nov 07 20:09:57 lc-ip123.inf.utfsm.cl mysqld[26907]: 2017-11-07T23:09:57.950122Z 0 [Note] Binlog end
    Nov 07 20:09:57 lc-ip123.inf.utfsm.cl mysqld[26907]: 2017-11-07T23:09:57.950324Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
    Nov 07 20:09:57 lc-ip123.inf.utfsm.cl systemd[1]: mysqld.service: control process exited, code=exited status=1
    Nov 07 20:09:57 lc-ip123.inf.utfsm.cl mysqld[26907]: Initialization of mysqld failed: 0
    Nov 07 20:09:57 lc-ip123.inf.utfsm.cl systemd[1]: Failed to start MySQL Server.
    -- Subject: Unit mysqld.service has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit mysqld.service has failed.
    -- 
    -- The result is failed.

Si completo el campo manualmente en /etc/my.cnf, el resultado es el siguiente:
  
    [ERROR] --initialize specified but the data directory has files in it. Aborting.
    [ERROR] Aborting

Esto usando /var/lib/mysql/opencart cono data directory.
Al usar /var/lib/mysql/ como data directory, el resultado es este error:

    Nov 07 20:55:17 lc-ip123.inf.utfsm.cl mysqld[17436]: Initialization of mysqld failed: 0
    Nov 07 20:55:17 lc-ip123.inf.utfsm.cl systemd[1]: mysqld.service: control process exited, code=exited status=1
    Nov 07 20:55:19 lc-ip123.inf.utfsm.cl systemd[1]: Failed to start MySQL Server.

no he encontrado otros logs utiles y al revisar el estado del daemon, en vez de estar en estado failed pasa a inactivo o activating/deactivating.

**Comment by mosoriob** [comment]
No he podido reproducir el error, no veo el log sobre el server-id.

**Comment by mosoriob** [comment]
Mira el log de error de mysql, tu lo tienes configurado en /var/lib/mysql/mysql-error.log 

cat /var/lib/mysql/mysql-error.log | grep -i error
