### ISSUE TITLE
Contraseña Consola AWS

### ISSUE THREAD

**Issue by fiturbe** [mosoriob/inf-323-questions#18]
Hola. en el archivo que está en moodle **no** aparece la contraseña con la que tenemos que ingresar a la consola https://691853262197.signin.aws.amazon.com/console

**Comment by mosoriob** [comment]
La contraseña no es necesaria
Revisa la siguiente documentación: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
