### ISSUE TITLE
issue #16: Reparando la configuración anterior

### ISSUE THREAD

**Issue by DanQuin** [mosoriob/inf-323-questions#2]
Cuando se enuncia "Configuración de logs por separado, favor el siguiente estandar /var/log/nginx/host.access.log (access y error)" a qué se refiere?
- El módulo [core](https://goo.gl/tRSJQH) define `error_log` y `acces_log` que supervisa las conexiones al servidor en general (cambiarlos ahí funcionará pero no considero que sea lo correcto, asumiendo que sea en la raíz del archivo (además de que se importa la configuración del _server\_block_.
- El módulo [http log](https://goo.gl/zkRjFy) incluye sólo la directiva de `access_log` y asume que el error lo manejará quien importa (es decir, se está en el caso de arriba).
La pregunta es: se necesita un `error_log` para el servidor? de ser así dónde se configura?.

**Comment by mosoriob** [comment]
Queremos los logs de access_log y error_log para cada serverblock. Así poder ver las visitas por ejemplo a un sitio o quizás más importante poder ver errores realizados al sitio. Como los errores 500 que generalmente son errores de cógido. Recuerda que en Linux hay niveles de log (debug, info, notice, warn, error, crit, alert o emerg), con los que puedes "jugar".

Los error_log se configuran con la sentencia error_log en el server_block (en este caso).
En otras palabras, el access_log y error_log van de la mano en cada serverblock.
