### ISSUE TITLE
Issue #14 Automatización 

### ISSUE THREAD

**Issue by fiturbe** [mosoriob/inf-323-questions#4]
Hola, para este issue necesitamos el ip de la segunda máquina, probé con la dada al inicio del curso (`10.10.15.194`) pero no conecta:
```
ssh root@10.10.15.194
ssh: connect to host 10.10.15.194 port 22: Network is unreachable
```
Otra cosa, hemos estado probando Ansible con la máquina que está funcionando haciendo las configuraciones iniciales de los host para que se logre conectar mediante `ssh`, el tema es que como estamos utilizando autenticación mediante llaves SSH, he visto que para configurarlo se debe definir el archivo donde se encuentra la llave privada con `ssh_private_key_file=/direccion/llave_privada`, el tema es que en la máquina como tal están solamente almacenadas las llaves de los otros computadores autorizados, por lo que no se puede definir como `ssh_private_key_file=/~/.ssh/id_rsa` ¿Cómo se configura en este caso?

**Comment by edmolten** [comment]
También busqué por todas partes y no encuentro las IPs

**Comment by mosoriob** [comment]
Recupere acceso a la 10.10.15.194, favor probar.

**Comment by mosoriob** [comment]
@edmolten https://moodle.inf.utfsm.cl/course/view.php?id=1286&section=2

**Comment by mosoriob** [comment]
Normalmente mi inventory
```
[produccion]
produccion ansible_host=10.6.91.188 server_id=1 ansible_ssh_private_key_file=/Users/mosorio/.ssh/linets
```
El  error debe ser el nombre de la variable, fijate que es ansible_ssh_private_key_file y no ssh_private_key_file

**Comment by fiturbe** [comment]
@sirspock, al intentar ingresar mediante ssh a la máquina (10.10.15.194) la clave no es la definida en el pdf :
```
ssh fiturbe@ssh2.inf.utfsm.cl
ssh root@10.10.15.194
root@10.10.15.194's password: 
Permission denied, please try again.
```

**Comment by mosoriob** [comment]
Favor revisar nuevamente.

**Comment by fiturbe** [comment]
@sirspock  ahora si, gracias!
