### ISSUE TITLE
Nos quedamos afuera de la máquina privada

### ISSUE THREAD

**Issue by fiturbe** [mosoriob/inf-323-questions#6]
Estábamos configurando Key based authentication por lo que:

1. Generamos las llaves en la máquina pública mediante `ssh-keygen`
2. Luego copiamos la llave a la máquina privada:
```
[root@grupo01-m1 .ssh]# ssh-copy-id -i ~/.ssh/ssh_key_machine_pub.pub root@10.10.15.194
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/root/.ssh/ssh_key_machine_pub.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
root@10.10.15.194's password: 

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh 'root@10.10.15.194'"
and check to make sure that only the key(s) you wanted were added.
```
3. Cambiamos en  `/etc/ssh/sshd_config` a `PasswordAuthentication no` y  reiniciamos el servicio

Luego de ello no hemos podido volver a ingresar a la máquina (10.10.15.194)  :(
Ayuda!

**Comment by mosoriob** [comment]
[root@grupo01-m1 ~]# ssh root@10.10.15.194 -i .ssh/ssh_key_machine_pub

**Comment by mosoriob** [comment]
Con la opción **-i**  pasas la llave privada especifica.

**Comment by fiturbe** [comment]
ohh! bueno :( 

Edit: Ahora si, gracias!!

**Comment by DanQuin** [comment]
@sirspock pero está bien pasarle el archivo con la clave pública (?), por qué tendríamos que entregarle la privada?
