### ISSUE TITLE
Automatización y nueva máquina

### ISSUE THREAD

**Issue by edmolten** [mosoriob/inf-323-questions#7]
¿Percona y Opencart deben estar en la nueva máquina?. De ser así, ¿ Su instalación es parte de la automatización?

**Comment by mosoriob** [comment]
Percona debe estar en la nueva máquina
Opencart no
En la automización no se lista tareas sobre percona (para simplificar la dificultad del laboratorio, en la realidad todo debiera estar automatizado)

**Comment by edmolten** [comment]
gracias
