### ISSUE TITLE
Issue #15 Nueva máquina

### ISSUE THREAD

**Issue by DanQuin** [mosoriob/inf-323-questions#8]
Una duda, cuando dice "Realizar las tareas básicas descritas en los issue anteriores en el nuevo servidor." se refiere sólo a lo de automatización? o también a cosas como servidor de hora, particionado, etc.?

**Comment by mosoriob** [comment]
Solos tareas enumeradas en la lista Para simplificar la dificultad del laboratorio, en la realidad todo debiera estar automatizado
