### ISSUE TITLE
Issue #17: Configurar certificado para el serverblock

### ISSUE THREAD

**Issue by horthp** [mosoriob/inf-323-questions#9]
Es normal que después de hacer la configuración con los certificados y el serverblock el sitio quede como no seguro ? :(

**Comment by mosoriob** [comment]
No, el certificado debe quedar bien.

¿Estás probando con grupoXX.mosorio.me verdad?

PD: Disculpa la demora, estaba viajando a una conferencia

**Comment by horthp** [comment]
Sip con grupo07.mosorio.me

**Comment by mosoriob** [comment]
No estabas utilizando el fullchain. Si colocas el certificado y la cadena (lo que tiene el archivo fullchain.pem) se soluciona.

La razón del problema de seguridad que muestra se habla en el [siguiente link](http://nginx.org/en/docs/http/configuring_https_servers.html) 
> Some browsers may complain about a certificate signed by a well-known certificate authority, while other browsers may accept the certificate without issues. This occurs because the issuing authority has signed the server certificate using an intermediate certificate that is not present in the certificate base of well-known trusted certificate authorities which is distributed with a particular browser. In this case the authority provides a bundle of chained certificates which should be concatenated to the signed server certificate. The server certificate must appear before the chained certificates in the combined file:

**Comment by horthp** [comment]
Use el fullchain y aun el sitio aparece como inseguro, no se que estoy haciendo mal D:

**Comment by mosoriob** [comment]
Antes no estaba con el fullchain, yo lo cambié. 
Yo lo veo bien, siempre para evitar problemas con el cache de tu navegador utiliza curl

```
curl -I https://grupo07.mosorio.me

HTTP/2 200 
server: nginx/1.12.1
date: Sat, 21 Oct 2017 19:38:47 GMT
content-type: text/html; charset=utf-8
x-powered-by: PHP/5.6.31
set-cookie: OCSESSID=129e08ed0c885ec822c767ef3f; path=/
set-cookie: OCSESSID=b0218cc2f2aa39fb30c6a9c47a; path=/
set-cookie: language=en-gb; expires=Mon, 20-Nov-2017 19:38:46 GMT; Max-Age=2592000; path=/; domain=grupo07.mosorio.me
set-cookie: currency=USD; expires=Mon, 20-Nov-2017 19:38:46 GMT; Max-Age=2592000; path=/; domain=grupo07.mosorio.me
strict-transport-security: max-age=15768000
```
